export interface Student {
    first: string;
    last: string;
    email: string;
    id: string;
    password: string;
    gender: string;
    phone: string;
    birth: string;
    institution: string;
}

export const studentData: Student[] = [
    {
        "first": "IETAC - XIMENA",
        "last": "ARIAS MANCO",
        "email": "sg.estudiante.ximena.arias",
        "id": "1066605786",
        "password": "Ximena.5786",
        "gender": "Mujer",
        "phone": "3213841433",
        "birth": "13 Nov 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - CAMILO ANDRÉS",
        "last": "ARROYO CASTRO",
        "email": "sg.estudiante.camilo.andres.arroyo",
        "id": "1066605793",
        "password": "CamiloA.5793",
        "gender": "Hombre",
        "phone": "3235647879",
        "birth": "05 Abr 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - MARÍA ESTHER",
        "last": "ACOSTA FERIA",
        "email": "sg.estudiante.maria.esther.acosta",
        "id": "1066605450",
        "password": "MaríaE.5450",
        "gender": "Mujer",
        "phone": "3105118499",
        "birth": "24 Oct 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JAIRO MANUEL",
        "last": "BALTAZAR VILLERO",
        "email": "sg.estudiante.jairo.manuel.baltazar",
        "id": "1063290755",
        "password": "JairoM.0755",
        "gender": "Hombre",
        "phone": "3146676105",
        "birth": "11 Oct 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JHOANS SEBASTIÁN",
        "last": "DURANGO ZABALA",
        "email": "sg.estudiante.jhoans.sebastian.durango",
        "id": "1063789927",
        "password": "JhoansS.9927",
        "gender": "Hombre",
        "phone": "3137974214",
        "birth": "20 Oct 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ELICEO ELI",
        "last": "FUENTES DÍAZ",
        "email": "sg.estudiante.eliceo.eli.fuentes",
        "id": "1133790795",
        "password": "EliceoE.0795",
        "gender": "Hombre",
        "phone": "3217064315",
        "birth": "19 Ago 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - LIZ VALERIA",
        "last": "GIL HOYOS",
        "email": "sg.estudiante.liz.valeria.gil",
        "id": "1063292674",
        "password": "LizV.2674",
        "gender": "Mujer",
        "phone": "3234030521",
        "birth": "18 Oct 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - HAROLD IVÁN",
        "last": "HOYOS VERGARA",
        "email": "sg.estudiante.harold.ivan.hoyos",
        "id": "1148438187",
        "password": "HaroldI.8187",
        "gender": "Hombre",
        "phone": "3122860764",
        "birth": "19 Mar 2008",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ISABELLA",
        "last": "MANCHEGO LOZANO",
        "email": "sg.estudiante.isabella.manchego",
        "id": "1063295017",
        "password": "Isabella.5017",
        "gender": "Mujer",
        "phone": "3206191655",
        "birth": "08 May 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - MARÍA ANGÉLICA",
        "last": "MORELO VILLEROS",
        "email": "sg.estudiante.maria.angelica.morelo",
        "id": "1070815365",
        "password": "MaríaA.5365",
        "gender": "Mujer",
        "phone": "3234365594",
        "birth": "13 Ago 2007",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - HERNÁN ANDRÉS",
        "last": "PALMERA PÉREZ",
        "email": "sg.estudiante.hernan.andres.palmera",
        "id": "1101447212",
        "password": "HernánA.7212",
        "gender": "Hombre",
        "phone": "3234839571",
        "birth": "02 Jun 2007",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ADRIANA LUCÍA",
        "last": "ROJAS CORDERO",
        "email": "sg.estudiante.adriana.lucia.rojas",
        "id": "1038117449",
        "password": "AdrianaL.7449",
        "gender": "Mujer",
        "phone": "3148090148",
        "birth": "04 Mar 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JOHAN ANDRÉS",
        "last": "SALCEDO BEDOYA",
        "email": "sg.estudiante.johan.andres.salcedo",
        "id": "1063290456",
        "password": "JohanA.0456",
        "gender": "Mujer",
        "phone": "3107241623",
        "birth": "14 Oct 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ARNEDIS",
        "last": "SIBAJA BEGAMBRE",
        "email": "sg.estudiante.arnedis.sibaja",
        "id": "1067898547",
        "password": "Arnedis.8547",
        "gender": "Mujer",
        "phone": "3235640423",
        "birth": "23 Mar 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ALEXANDRA",
        "last": "URZOLA MARTÍNEZ",
        "email": "sg.estudiante.alexandra.urzola",
        "id": "1066605887",
        "password": "Alexandra.5887",
        "gender": "Hombre",
        "phone": "3128989638",
        "birth": "04 Mar 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - DANIEL ANDRÉS",
        "last": "ZABALA MONTIEL",
        "email": "sg.estudiante.daniel.andres.zabala",
        "id": "1066606169",
        "password": "DanielA.6169",
        "gender": "Hombre",
        "phone": "3114262393",
        "birth": "10 Abr 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - LUIS MARIO",
        "last": "ZABALA SÁNCHEZ",
        "email": "sg.estudiante.luis.mario.zabala",
        "id": "114869587",
        "password": "LuisM.9587",
        "gender": "Mujer",
        "phone": "3104004760",
        "birth": "07 Sep 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - RONALDO ANDRÉS",
        "last": "ZULETA GUERRA",
        "email": "sg.estudiante.ronaldo.andres.zuleta",
        "id": "1033373778",
        "password": "RonaldoA.3778",
        "gender": "Mujer",
        "phone": "3133984933",
        "birth": "01 Mar 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - KAREN SOFÍA",
        "last": "ARRIETA VERGARA",
        "email": "sg.estudiante.karen.sofia.arrieta",
        "id": "1063292595",
        "password": "KarenS.2595",
        "gender": "Mujer",
        "phone": "3148177142",
        "birth": "17 Abr 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ANA BELÉN",
        "last": "BARÓN CEBALLOS",
        "email": "sg.estudiante.ana.belen.baron",
        "id": "1066572003",
        "password": "AnaB.2003",
        "gender": "Hombre",
        "phone": "3217229477",
        "birth": "30 Sep 2007",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - KAREN DAYANA",
        "last": "CASTILLO PÉREZ",
        "email": "sg.estudiante.karen.dayana.castillo",
        "id": "1148695425",
        "password": "KarenD.5425",
        "gender": "Hombre",
        "phone": "3105074210",
        "birth": "11 Feb 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JUAN DAVID",
        "last": "CORREA HERNÁNDEZ",
        "email": "sg.estudiante.juan.david.correa",
        "id": "1148695426",
        "password": "JuanD.5426",
        "gender": "Mujer",
        "phone": "3216335419",
        "birth": "10 Feb 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - LUIS DANIEL",
        "last": "MENDOZA URIBE",
        "email": "sg.estudiante.luis.daniel.mendoza",
        "id": "1133790727",
        "password": "LuisD.0727",
        "gender": "Mujer",
        "phone": "3237650952",
        "birth": "10 Sep 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ALEXANDRA",
        "last": "JULIO ROMERO",
        "email": "sg.estudiante.alexandra.julio",
        "id": "1066573694",
        "password": "Alexandra.3694",
        "gender": "Mujer",
        "phone": "3108218930",
        "birth": "16 Ene 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - YULISA",
        "last": "RODRÍGUEZ RODRÍGUEZ",
        "email": "sg.estudiante.yulisa.rodriguez",
        "id": "1063295162",
        "password": "Yulisa.5162",
        "gender": "Hombre",
        "phone": "3145180611",
        "birth": "19 Jun 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - VIVIANA MARCELA",
        "last": "ROMERO ZÚÑIGA",
        "email": "sg.estudiante.viviana.marcela.romero",
        "id": "1148438017",
        "password": "VivianaM.8017",
        "gender": "Mujer",
        "phone": "3148441560",
        "birth": "06 Feb 2008",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - DAINER ANDRÉS",
        "last": "SÁNCHEZ CASTRO",
        "email": "sg.estudiante.dainer.andres.sanchez",
        "id": "1148695511",
        "password": "DainerA.5511",
        "gender": "Hombre",
        "phone": "3105353181",
        "birth": "03 Abr 2009",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - MARIANA DE",
        "last": "JESÚS CABADIA PARRA",
        "email": "sg.estudiante.mariana.de.jesus",
        "id": "1067286561",
        "password": "MarianaD.6561",
        "gender": "Hombre",
        "phone": "3148945915",
        "birth": "06 Jul 2007",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JANER",
        "last": "CASTRO MONTALVO",
        "email": "sg.estudiante.janer.castro",
        "id": "1063293969",
        "password": "Janer.3969",
        "gender": "Mujer",
        "phone": "3025714175",
        "birth": "21 Jun 2008",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - DAVIER ESTEBAN",
        "last": "OTERO URANGO",
        "email": "sg.estudiante.davier.esteban.otero",
        "id": "1148437906",
        "password": "DavierE.7906",
        "gender": "Mujer",
        "phone": "3114062955",
        "birth": "15 Dic 2008",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - ELIANA MARCELA",
        "last": "VERGARA GANDIA",
        "email": "sg.estudiante.eliana.marcela.vergara",
        "id": "1148695420",
        "password": "ElianaM.5420",
        "gender": "Hombre",
        "phone": "3146640429",
        "birth": "14 Mar 2010",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - LUISA FERNANDA",
        "last": "BARÓN LUCAS",
        "email": "sg.estudiante.luisa.fernanda.baron",
        "id": "1133790340",
        "password": "LuisaF.0340",
        "gender": "Mujer",
        "phone": "3218863178",
        "birth": "12 Oct 2004",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - JORGE ANDRÉS",
        "last": "PÉREZ MESTRA",
        "email": "sg.estudiante.jorge.andres.perez",
        "id": "1148438554",
        "password": "JorgeA.8554",
        "gender": "Mujer",
        "phone": "3012478928",
        "birth": "17 Dic 2008",
        "institution": "IETAC"
    },
    {
        "first": "IETAC - YULEIMIS",
        "last": "MURILLO GÓMEZ",
        "email": "sg.estudiante.yuleimis.murillo",
        "id": "1148695628",
        "password": "Yuleimis.5628",
        "gender": "Mujer",
        "phone": "3218976781",
        "birth": "06 May 2010",
        "institution": "IETAC"
    },
    {
        "first": "SG - JOHAN ANDRÉS",
        "last": "SALCEDO BEDOYA",
        "email": "sg.estudiante.johan.andres.salcedo",
        "id": "1066606386",
        "password": "JohanA.6386",
        "gender": "Hombre",
        "phone": "3117930027",
        "birth": "10 Oct 2010",
        "institution": "SG"
    },
    {
        "first": "SG - RONALDO ANDRES",
        "last": "ZULETA GUERRA",
        "email": "sg.estudiante.ronaldo.andres.zuleta",
        "id": "1063363727",
        "password": "RonaldoA.3727",
        "gender": "Hombre",
        "phone": "3127038167",
        "birth": "7 Abr 2010",
        "institution": "SG"
    },
    {
        "first": "SG - ANGIE SOFIA",
        "last": "ALDANA ARIAS",
        "email": "sg.estudiante.angie.sofia.aldana",
        "id": "1014992221",
        "password": "AngieS.2221",
        "gender": "Mujer",
        "phone": "3227514890",
        "birth": "15 Ene 2009",
        "institution": "SG"
    },
    {
        "first": "SG - LUIS FELIPE",
        "last": "ESCUDERO VILLEGAS",
        "email": "sg.estudiante.luis.felipe.escudero",
        "id": "1013126436",
        "password": "LuisF.6436",
        "gender": "Hombre",
        "phone": "3155547519",
        "birth": "10 May 2009",
        "institution": "SG"
    },
    {
        "first": "SG - LAURA SOFÍA",
        "last": "OVEJERO MALDONADO",
        "email": "sg.estudiante.laura.sofia.ovejero",
        "id": "1115690260",
        "password": "LauraS.0260",
        "gender": "Mujer",
        "phone": "3208561077",
        "birth": "8 Ago 2007",
        "institution": "SG"
    },
    {
        "first": "SG - KAMILA INES",
        "last": "HERRERA MARTINEZ",
        "email": "sg.estudiante.kamila.ines.herrera",
        "id": "1049935197",
        "password": "KamilaI.5197",
        "gender": "Mujer",
        "phone": "3207512318",
        "birth": "28 Abr 2009",
        "institution": "SG"
    },
    {
        "first": "SG - VALERIE",
        "last": "GAMARRA FONTALVO",
        "email": "sg.estudiante.valerie.gamarra",
        "id": "1041981827",
        "password": "Valerie.1827",
        "gender": "Mujer",
        "phone": "3008411890",
        "birth": "21 Mar 2008",
        "institution": "SG"
    },
    {
        "first": "SG - KAROL VALENTINA",
        "last": "CEBALLOS QUIROZ",
        "email": "sg.estudiante.karol.valentina.ceballos",
        "id": "1080052959",
        "password": "KarolV.2959",
        "gender": "Mujer",
        "phone": "3186066577",
        "birth": "11 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - ANGIE CAROLINA",
        "last": "SOTO GIRALDO",
        "email": "sg.estudiante.angie.carolina.soto",
        "id": "1063158765",
        "password": "AngieC.8765",
        "gender": "Mujer",
        "phone": "3015412469",
        "birth": "16 Dic 2009",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN DIEGO",
        "last": "ZAMBRANO OCAMPO",
        "email": "sg.estudiante.juan.diego.zambrano",
        "id": "1077726158",
        "password": "JuanD.6158",
        "gender": "Hombre",
        "phone": "3219208778",
        "birth": "13 Ene 2009",
        "institution": "SG"
    },
    {
        "first": "SG - STEPHANY",
        "last": "VELAZCO RODRIGUEZ",
        "email": "sg.estudiante.stephany.velazco",
        "id": "1142715366",
        "password": "Stephany.5366",
        "gender": "Mujer",
        "phone": "3227895263",
        "birth": "29 Feb 2008",
        "institution": "SG"
    },
    {
        "first": "SG - ISABELA",
        "last": "BARREIRO CÁRDENAS",
        "email": "sg.estudiante.isabela.barreiro",
        "id": "1077230281",
        "password": "Isabela.0281",
        "gender": "Mujer",
        "phone": "3182445710",
        "birth": "5 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN SEBASTIAN",
        "last": "RIVERA AVENDAÑO",
        "email": "sg.estudiante.juan.sebastian.rivera",
        "id": "1051066924",
        "password": "JuanS.6924",
        "gender": "Hombre",
        "phone": "3232363008",
        "birth": "3 Feb 2006",
        "institution": "SG"
    },
    {
        "first": "SG - KAREN YULIED",
        "last": "ARENAS COMETA",
        "email": "sg.estudiante.karen.yulied.arenas",
        "id": "1061717282",
        "password": "KarenY.7282",
        "gender": "Mujer",
        "phone": "3217962477",
        "birth": "16 Mar 2007",
        "institution": "SG"
    },
    {
        "first": "SG - LUIS ANTONIO",
        "last": "MUÑOZ HINCAPIE",
        "email": "sg.estudiante.luis.antonio.munoz",
        "id": "1104821599",
        "password": "LuisA.1599",
        "gender": "Hombre",
        "phone": "3173072374",
        "birth": "3 Abr 2009",
        "institution": "SG"
    },
    {
        "first": "SG - ADRIANA ISABEL",
        "last": "HOYOS HOYOS",
        "email": "sg.estudiante.adriana.isabel.hoyos",
        "id": "1103950959",
        "password": "AdrianaI.0959",
        "gender": "Mujer",
        "phone": "3117555971",
        "birth": "28 Abr 2010",
        "institution": "SG"
    },
    {
        "first": "SG - CAREN YILENI",
        "last": "ECHEVERRÍA CARDOZO",
        "email": "sg.estudiante.caren.yileni.echeverria",
        "id": "1099205249",
        "password": "CarenY.5249",
        "gender": "Mujer",
        "phone": "3103011277",
        "birth": "6 Jul 2006",
        "institution": "SG"
    },
    {
        "first": "SG - JOSIAS",
        "last": "ACUÑA ARIAS",
        "email": "sg.estudiante.josias.acuna",
        "id": "1128327871",
        "password": "Josias.7871",
        "gender": "Hombre",
        "phone": "3135423557",
        "birth": "23 Feb 2010",
        "institution": "SG"
    },
    {
        "first": "SG - CRISTIAN DE",
        "last": "JESÚS CUESTA BLANQUICETT",
        "email": "sg.estudiante.cristian.de.jesus",
        "id": "1043975755",
        "password": "CristianD.5755",
        "gender": "Hombre",
        "phone": "3244710853",
        "birth": "6 Nov 2007",
        "institution": "SG"
    },
    {
        "first": "SG - NATALIA",
        "last": "CARVAJAL VERGARA",
        "email": "sg.estudiante.natalia.carvajal",
        "id": "1104547717",
        "password": "Natalia.7717",
        "gender": "Mujer",
        "phone": "3178001109",
        "birth": "30 Dic 2008",
        "institution": "SG"
    },
    {
        "first": "SG - SAHRA ELIZABETH",
        "last": "PUJIMUY ROBLES",
        "email": "sg.estudiante.sahra.elizabeth.pujimuy",
        "id": "1120099332",
        "password": "SahraE.9332",
        "gender": "Mujer",
        "phone": "3150301936",
        "birth": "14 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - MATHIAS JOSÉ",
        "last": "HERNÁNDEZ BERMÚDEZ",
        "email": "sg.estudiante.mathias.jose.hernandez",
        "id": "1143241184",
        "password": "MathiasJ.1184",
        "gender": "Hombre",
        "phone": "3014610172",
        "birth": "2 Feb 2010",
        "institution": "SG"
    },
    {
        "first": "SG - MIGUEL ANGEL",
        "last": "AYALA PRIETO",
        "email": "sg.estudiante.miguel.angel.ayala",
        "id": "1098678852",
        "password": "MiguelA.8852",
        "gender": "Hombre",
        "phone": "3222935686",
        "birth": "27 Nov 2007",
        "institution": "SG"
    },
    {
        "first": "SG - SANTIAGO",
        "last": "SERNA MEDINA",
        "email": "sg.estudiante.santiago.serna",
        "id": "1022367201",
        "password": "Santiago.7201",
        "gender": "Hombre",
        "phone": "3235239683",
        "birth": "14 Feb 2009",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN CAMILO",
        "last": "URIBE CUESTA",
        "email": "sg.estudiante.juan.camilo.uribe",
        "id": "1142921241",
        "password": "JuanC.1241",
        "gender": "Hombre",
        "phone": "3053068087",
        "birth": "16 Oct 2008",
        "institution": "SG"
    },
    {
        "first": "SG - YURI NATALIA",
        "last": "SARMIENTO SILVA",
        "email": "sg.estudiante.yuri.natalia.sarmiento",
        "id": "1095530126",
        "password": "YuriN.0126",
        "gender": "Mujer",
        "phone": "3134816142",
        "birth": "31 Oct 2008",
        "institution": "SG"
    },
    {
        "first": "SG - BRITANI MARIANGEL",
        "last": "AGUERO GARCIA",
        "email": "sg.estudiante.britani.mariangel.aguero",
        "id": "7734824",
        "password": "BritaniM.4824",
        "gender": "Mujer",
        "phone": "3225322813",
        "birth": "14 Abr 2009",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA JOSÉ",
        "last": "CORTES CHALITAS",
        "email": "sg.estudiante.maria.jose.cortes",
        "id": "1061741898",
        "password": "MaríaJ.1898",
        "gender": "Mujer",
        "phone": "3104676773",
        "birth": "22 Sep 2009",
        "institution": "SG"
    },
    {
        "first": "SG - SOFIA",
        "last": "MÚNERA LÓPEZ",
        "email": "sg.estudiante.sofia.munera",
        "id": "1143340255",
        "password": "Sofia.0255",
        "gender": "Mujer",
        "phone": "3218194765",
        "birth": "25 Ene 2008",
        "institution": "SG"
    },
    {
        "first": "SG - ROSA INES",
        "last": "REVEROL GONZALEZ",
        "email": "sg.estudiante.rosa.ines.reverol",
        "id": "5420076",
        "password": "RosaI.0076",
        "gender": "Mujer",
        "phone": "3166414003",
        "birth": "17 Mar 2006",
        "institution": "SG"
    },
    {
        "first": "SG - SALOME",
        "last": "DUQUE BETANCURT",
        "email": "sg.estudiante.salome.duque",
        "id": "1088826978",
        "password": "Salome.6978",
        "gender": "Mujer",
        "phone": "3122342082",
        "birth": "9 Oct 2005",
        "institution": "SG"
    },
    {
        "first": "SG - ROSA",
        "last": "MENDIETA FONSECA",
        "email": "sg.estudiante.rosa.mendieta",
        "id": "1097912847",
        "password": "Rosa.2847",
        "gender": "Mujer",
        "phone": "3189815815",
        "birth": "2 May 2008",
        "institution": "SG"
    },
    {
        "first": "SG - JHOAN DAVID",
        "last": "LEÓN LAGOS",
        "email": "sg.estudiante.jhoan.david.leon",
        "id": "1118366654",
        "password": "JhoanD.6654",
        "gender": "Hombre",
        "phone": "3165125489",
        "birth": "16 Jul 2007",
        "institution": "SG"
    },
    {
        "first": "SG - LUIS FERNANDO",
        "last": "LOPEZ LOPEZ",
        "email": "sg.estudiante.luis.fernando.lopez",
        "id": "1112465416",
        "password": "LuisF.5416",
        "gender": "Hombre",
        "phone": "3183686853",
        "birth": "6 Jun 1988",
        "institution": "SG"
    },
    {
        "first": "SG - TALIANA ANDREA",
        "last": "FLOREZ SALGADO",
        "email": "sg.estudiante.taliana.andrea.florez",
        "id": "1062437352",
        "password": "TalianaA.7352",
        "gender": "Mujer",
        "phone": "3223162668",
        "birth": "30 Ago 2008",
        "institution": "SG"
    },
    {
        "first": "SG - EMMA ISABELLA",
        "last": "LINDADO ALGARIN",
        "email": "sg.estudiante.emma.isabella.lindado",
        "id": "1043594698",
        "password": "EmmaI.4698",
        "gender": "Mujer",
        "phone": "3016384917",
        "birth": "3 Jul 2010",
        "institution": "SG"
    },
    {
        "first": "SG - CLAUDIA VALENTINA",
        "last": "OSORIO GOMEZ",
        "email": "sg.estudiante.claudia.valentina.osorio",
        "id": "1126704313",
        "password": "ClaudiaV.4313",
        "gender": "Mujer",
        "phone": "3167862555",
        "birth": "6 Dic 2006",
        "institution": "SG"
    },
    {
        "first": "SG - DANIELA SOFÍA",
        "last": "FLOREZ VARGAS",
        "email": "sg.estudiante.daniela.sofia.florez",
        "id": "1023381412",
        "password": "DanielaS.1412",
        "gender": "Mujer",
        "phone": "3224701279",
        "birth": "28 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - MARIANA",
        "last": "DÍAZ ZÚÑIGA",
        "email": "sg.estudiante.mariana.diaz",
        "id": "1110296142",
        "password": "Mariana.6142",
        "gender": "Mujer",
        "phone": "3226409571",
        "birth": "9 May 2008",
        "institution": "SG"
    },
    {
        "first": "SG - MARIA PAULA",
        "last": "CARBALLO QUINTERO",
        "email": "sg.estudiante.maria.paula.carballo",
        "id": "1095925977",
        "password": "MariaP.5977",
        "gender": "Mujer",
        "phone": "3132678363",
        "birth": "25 Jul 2009",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN FRANCISCO",
        "last": "CAMACHO POSSO",
        "email": "sg.estudiante.juan.francisco.camacho",
        "id": "1023084237",
        "password": "JuanF.4237",
        "gender": "Hombre",
        "phone": "3015776049",
        "birth": "16 May 2007",
        "institution": "SG"
    },
    {
        "first": "SG - NICOLLE",
        "last": "MARMOLEJO LUNA",
        "email": "sg.estudiante.nicolle.marmolejo",
        "id": "1047430590",
        "password": "Nicolle.0590",
        "gender": "Mujer",
        "phone": "3024017720",
        "birth": "21 Ene 2009",
        "institution": "SG"
    },
    {
        "first": "SG - CAMILA ALEJANDRA",
        "last": "RAMIREZ RUEDA",
        "email": "sg.estudiante.camila.alejandra.ramirez",
        "id": "1016036708",
        "password": "CamilaA.6708",
        "gender": "Mujer",
        "phone": "3215083338",
        "birth": "9 Jul 2009",
        "institution": "SG"
    },
    {
        "first": "SG - MARGREYS",
        "last": "QUINTERO PALOMINO",
        "email": "sg.estudiante.margreys.quintero",
        "id": "1043658548",
        "password": "Margreys.8548",
        "gender": "Mujer",
        "phone": "3113244504",
        "birth": "23 Jun 2008",
        "institution": "SG"
    },
    {
        "first": "SG - DANIEL FELIPE",
        "last": "MOTTA PILONIETA",
        "email": "sg.estudiante.daniel.felipe.motta",
        "id": "1146334161",
        "password": "DanielF.4161",
        "gender": "Hombre",
        "phone": "3132093991",
        "birth": "26 Jul 2007",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA PAULA",
        "last": "TAPIA YEPES",
        "email": "sg.estudiante.maria.paula.tapia",
        "id": "1062439947",
        "password": "MaríaP.9947",
        "gender": "Mujer",
        "phone": "3208009060",
        "birth": "2 Jul 2009",
        "institution": "SG"
    },
    {
        "first": "SG - GABRIEL",
        "last": "SUTACHAN MENDEZ",
        "email": "sg.estudiante.gabriel.sutachan",
        "id": "1025062800",
        "password": "Gabriel.2800",
        "gender": "Hombre",
        "phone": "3146841501",
        "birth": "9 Ago 2007",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA JULIETH",
        "last": "CASTILLO BAUTISTA",
        "email": "sg.estudiante.maria.julieth.castillo",
        "id": "1097102695",
        "password": "MaríaJ.2695",
        "gender": "Mujer",
        "phone": "3244027640",
        "birth": "20 Oct 2008",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN JOSE",
        "last": "CASTILLO VIVERO",
        "email": "sg.estudiante.juan.jose.castillo",
        "id": "1102826203",
        "password": "JuanJ.6203",
        "gender": "Hombre",
        "phone": "3128513898",
        "birth": "1 Sep 2007",
        "institution": "SG"
    },
    {
        "first": "SG - DIANA MARCELA",
        "last": "MANBUSCAY AGUDELO",
        "email": "sg.estudiante.diana.marcela.manbuscay",
        "id": "1028663171",
        "password": "DianaM.3171",
        "gender": "Mujer",
        "phone": "3218623435",
        "birth": "22 Feb 2007",
        "institution": "SG"
    },
    {
        "first": "SG - GISELL LETIZIA",
        "last": "DUARTE CALDERÓN",
        "email": "sg.estudiante.gisell.letizia.duarte",
        "id": "1097495125",
        "password": "GisellL.5125",
        "gender": "Mujer",
        "phone": "3123914307",
        "birth": "26 Nov 2006",
        "institution": "SG"
    },
    {
        "first": "SG - VALERIA",
        "last": "AUSECHA CAMPO",
        "email": "sg.estudiante.valeria.ausecha",
        "id": "1058933116",
        "password": "Valeria.3116",
        "gender": "Mujer",
        "phone": "3145535358",
        "birth": "22 May 2007",
        "institution": "SG"
    },
    {
        "first": "SG - KIARA",
        "last": "CALDERA CORONADO",
        "email": "sg.estudiante.kiara.caldera",
        "id": "1169713061",
        "password": "Kiara.3061",
        "gender": "Mujer",
        "phone": "3006586295",
        "birth": "22 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - DULCE MARÍA",
        "last": "ROJAS TARAZONA",
        "email": "sg.estudiante.dulce.maria.rojas",
        "id": "1093434369",
        "password": "DulceM.4369",
        "gender": "Mujer",
        "phone": "3180921910",
        "birth": "14 Dic 2009",
        "institution": "SG"
    },
    {
        "first": "SG - ÁNGEL",
        "last": "GABRIEL GÓMEZ",
        "email": "sg.estudiante.angel.gabriel",
        "id": "1080053987",
        "password": "Ángel.3987",
        "gender": "Hombre",
        "phone": "3148312462",
        "birth": "24 Nov 2008",
        "institution": "SG"
    },
    {
        "first": "SG - KEVIN SANTIAGO",
        "last": "PORTILLO BENAVIDES",
        "email": "sg.estudiante.kevin.santiago.portillo",
        "id": "1080052995",
        "password": "KevinS.2995",
        "gender": "Hombre",
        "phone": "3174204485",
        "birth": "17 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA PAULA",
        "last": "PÉREZ HORMIGA",
        "email": "sg.estudiante.maria.paula.perez",
        "id": "1058547636",
        "password": "MaríaP.7636",
        "gender": "Mujer",
        "phone": "3225820955",
        "birth": "23 Jul 2005",
        "institution": "SG"
    },
    {
        "first": "SG - MARIA JOSE",
        "last": "GUTIERREZ OSORIO",
        "email": "sg.estudiante.maria.jose.gutierrez",
        "id": "1114241878",
        "password": "MariaJ.1878",
        "gender": "Mujer",
        "phone": "3136423686",
        "birth": "6 Ago 2007",
        "institution": "SG"
    },
    {
        "first": "SG - LAURA CAMILA",
        "last": "GUZMÁN LÓPEZ",
        "email": "sg.estudiante.laura.camila.guzman",
        "id": "1059242362",
        "password": "LauraC.2362",
        "gender": "Mujer",
        "phone": "3232331239",
        "birth": "27 May 2009",
        "institution": "SG"
    },
    {
        "first": "SG - JUAN ANDRES",
        "last": "ECHEVERRÍA ESCOBAR",
        "email": "sg.estudiante.juan.andres.echeverria",
        "id": "1044637051",
        "password": "JuanA.7051",
        "gender": "Hombre",
        "phone": "3233366869",
        "birth": "9 Dic 2009",
        "institution": "SG"
    },
    {
        "first": "SG - MARIA JOSE",
        "last": "OSSA CUERVO",
        "email": "sg.estudiante.maria.jose.ossa",
        "id": "1055359068",
        "password": "MariaJ.9068",
        "gender": "Mujer",
        "phone": "3215863907",
        "birth": "20 Sep 2005",
        "institution": "SG"
    },
    {
        "first": "SG - SAMARA",
        "last": "CARO ORTEGA",
        "email": "sg.estudiante.samara.caro",
        "id": "1042587442",
        "password": "Samara.7442",
        "gender": "Mujer",
        "phone": "3114600284",
        "birth": "5 Mar 2010",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA DANIELA",
        "last": "VERA VILLAMIZAR",
        "email": "sg.estudiante.maria.daniela.vera",
        "id": "1096069283",
        "password": "MaríaD.9283",
        "gender": "Mujer",
        "phone": "3151955263",
        "birth": "3 Oct 2009",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA ALEJANDRA",
        "last": "RODRIGUEZ CANDURY",
        "email": "sg.estudiante.maria.alejandra.rodriguez",
        "id": "1044918208",
        "password": "MaríaA.8208",
        "gender": "Mujer",
        "phone": "3044575457",
        "birth": "16 Dic 2008",
        "institution": "SG"
    },
    {
        "first": "SG - CRISTIAN DAVID",
        "last": "FAJARDO PERILLA",
        "email": "sg.estudiante.cristian.david.fajardo",
        "id": "1050096058",
        "password": "CristianD.6058",
        "gender": "Hombre",
        "phone": "3209444893",
        "birth": "4 Mar 2010",
        "institution": "SG"
    },
    {
        "first": "SG - MARLONG FRRNEY",
        "last": "CASAS RONDON",
        "email": "sg.estudiante.marlong.frrney.casas",
        "id": "1030280214",
        "password": "MarlongF.0214",
        "gender": "Hombre",
        "phone": "3212128851",
        "birth": "24 Oct 2006",
        "institution": "SG"
    },
    {
        "first": "SG - DARLY SARAY",
        "last": "PÉREZ JAIMES",
        "email": "sg.estudiante.darly.saray.perez",
        "id": "1098073581",
        "password": "DarlyS.3581",
        "gender": "Mujer",
        "phone": "3167176810",
        "birth": "10 Abr 2008",
        "institution": "SG"
    },
    {
        "first": "SG - SALOMÉ",
        "last": "DIAZ VALENCIA",
        "email": "sg.estudiante.salome.diaz",
        "id": "1110296676",
        "password": "Salomé.6676",
        "gender": "Mujer",
        "phone": "3152053753",
        "birth": "26 Sep 2008",
        "institution": "SG"
    },
    {
        "first": "SG - JULIETH VANESSA",
        "last": "BECERRA MORA",
        "email": "sg.estudiante.julieth.vanessa.becerra",
        "id": "1097496452",
        "password": "JuliethV.6452",
        "gender": "Mujer",
        "phone": "3174938697",
        "birth": "20 Jun 2007",
        "institution": "SG"
    },
    {
        "first": "SG - DANIELA",
        "last": "MANCHOLA TORRES",
        "email": "sg.estudiante.daniela.manchola",
        "id": "1105840578",
        "password": "Daniela.0578",
        "gender": "Mujer",
        "phone": "3213254051",
        "birth": "10 Jun 2010",
        "institution": "SG"
    },
    {
        "first": "SG - GABRIELA",
        "last": "CASTIBLANCO WILCHES",
        "email": "sg.estudiante.gabriela.castiblanco",
        "id": "1065892631",
        "password": "Gabriela.2631",
        "gender": "Mujer",
        "phone": "3216879376",
        "birth": "29 Sep 2010",
        "institution": "SG"
    },
    {
        "first": "SG - MARÍA FERNANDA",
        "last": "SANTANA RAMÍREZ",
        "email": "sg.estudiante.maria.fernanda.santana",
        "id": "1065893790",
        "password": "MaríaF.3790",
        "gender": "Mujer",
        "phone": "3189253802",
        "birth": "28 Dic 2010",
        "institution": "SG"
    },
    {
        "first": "SG - ANDREA VALENTINA",
        "last": "RAMÍREZ OCHOA",
        "email": "sg.estudiante.andrea.valentina.ramirez",
        "id": "1053787841",
        "password": "AndreaV.7841",
        "gender": "Mujer",
        "phone": "3223860087",
        "birth": "4 Ago 2006",
        "institution": "SG"
    },
    {
        "first": "SG - VALENTINA",
        "last": "ESPINOSA ARIAS",
        "email": "sg.estudiante.valentina.espinosa",
        "id": "1106633208",
        "password": "Valentina.3208",
        "gender": "Mujer",
        "phone": "3172530404",
        "birth": "29 Ene 2006",
        "institution": "SG"
    },
    {
        "first": "SG - SHEYLA DE",
        "last": "JESUS AVILEZ VEGA",
        "email": "sg.estudiante.sheyla.de.jesus",
        "id": "1069485344",
        "password": "SheylaD.5344",
        "gender": "Mujer",
        "phone": "3113407450",
        "birth": "8 Jun 2025",
        "institution": "SG"
    },
    {
        "first": "SG - SARA SOFIA",
        "last": "ESQUIVEL VARGAS",
        "email": "sg.estudiante.sara.sofia.esquivel",
        "id": "1077726354",
        "password": "SaraS.6354",
        "gender": "Mujer",
        "phone": "3112649339",
        "birth": "4 Feb 2009",
        "institution": "SG"
    },
    {
        "first": "SG - LORENA ALEJANDRA",
        "last": "POVEDA QUIÑONES",
        "email": "sg.estudiante.lorena.alejandra.poveda",
        "id": "1011092218",
        "password": "LorenaA.2218",
        "gender": "Mujer",
        "phone": "3114033466",
        "birth": "28 Feb 2006",
        "institution": "SG"
    },
    {
        "first": "SG - JULIANA",
        "last": "BORJA BUELVAS",
        "email": "sg.estudiante.juliana.borja",
        "id": "1062440492",
        "password": "Juliana.0492",
        "gender": "Mujer",
        "phone": "3242781399",
        "birth": "3 Oct 2009",
        "institution": "SG"
    },
    {
        "first": "SG - LEYSA LUZ",
        "last": "MARTINEZ MENDOZA",
        "email": "sg.estudiante.leysa.luz.martinez",
        "id": "1104261261",
        "password": "LeysaL.1261",
        "gender": "Mujer",
        "phone": "3012351902",
        "birth": "4 Mar 2008",
        "institution": "SG"
    },
    {
        "first": "SG - ALEJANDRO DAVID",
        "last": "LORA TORRES",
        "email": "sg.estudiante.alejandro.david.lora",
        "id": "1028006716",
        "password": "AlejandroD.6716",
        "gender": "Hombre",
        "phone": "3017327165",
        "birth": "16 Feb 2010",
        "institution": "SG"
    }
];
